[project]
name = "langchain-with-knowledgegraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipynb>=0.5.1",
    "kernel>=0.12.0",
    "langchain>=0.3.27",
    "langchain-experimental>=0.3.4",
]
